name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: "4alonkellner/lintok-ci:latest"
      env:
        PATH: "/github/home/.local/bin:${{ env.PATH }}"
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - uses: actions/checkout@v4
      - name: postCreateCommand
        run: .devcontainer/postCreateCommand
      - name: postStartCommand & pre-commit all
        run: .devcontainer/postStartCommand
