name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: "4alonkellner/lintok-ci:latest"
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - uses: actions/checkout@v4
      - name: debug
        run: |
          pwd
          ls -a
          git config --global --add safe.directory $(pwd)
          git config --list --show-origin
      - name: postCreateCommand
        run: .devcontainer/postCreateCommand || cat /github/home/.cache/pre-commit/pre-commit.log
      - name: postStartCommand & pre-commit all
        run: .devcontainer/postStartCommand
