name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - uses: actions/checkout@v4
      - uses: tox-dev/action-pre-commit-uv@v1
